/**
 * This method was generated by MyBatis Generator.
 * This method corresponds to the database table g_users
 *
 * @mbg.generated Sun Aug 13 20:54:51 CST 2017
 */
protected Criteria createCriteriaInternal(){
    Criteria criteria = new Criteria();
    return criteria;
}